#!/bin/bash
#
# Copyright 2015 Battams, Derek
# 
#	Licensed under the Apache License, Version 2.0 (the "License");
#	you may not use this file except in compliance with the License.
#	You may obtain a copy of the License at
# 
#		http://www.apache.org/licenses/LICENSE-2.0
#
#	Unless required by applicable law or agreed to in writing, software
#	distributed under the License is distributed on an "AS IS" BASIS,
#	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#	limitations under the License.
#
JVM_OPTS=
if [[ "$DEBUG_PSMTP" == "1" ]]; then
	JVM_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
fi
export JAVA_OPTIONS=$JVM_OPTS